language: android
android:
  components:
    - build-tools-28.0.3
    - android-27
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  script:
  - ./gradlew clean test build