version: 2
jobs:
  build:
    working_directory: ~/Acceptic
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew clean -x lintDebug testDebug assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
    parallelism: 4
workflows:
  version: 2
  build:
    jobs:
      - build