version: 2
jobs:
  build:
    working_directory: ~/Acceptic
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew clean -x lintDebug  assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - hold:
          type: approval # requires that an in-app button be clicked by an appropriate member of the project to continue.
          requires:
            - store_artifacts
      - store_test_results:
          path: app/build/test-results
          requires:
            - hold
workflows:
  version: 2
  build:
    jobs:
      - build