version: 2
jobs:
  build:
    working_directory: ~/Acceptic
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew clean -x lintDebug  assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  print:
    working_directory: ~/Acceptic
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name : Variables
          command: |
            echo "$CI $CI_PULL_REQUEST $CIRCLE_BRANCH $CIRCLE_BUILD_NUM $CIRCLE_BUILD_URL $CIRCLE_COMPARE_URL"
            echo "$CIRCLE_PULL_REQUEST $CIRCLE_JOB"
      - run:
          name : Just print
          command: ./.circleci/build.sh $CIRCLE_BUILD_NUM
workflows:
  version: 2
  build:
    jobs:
      - print