version: 2
jobs:
  build:
    working_directory: ~/Acceptic
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew clean -x lintDebug  assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
workflows:
  version: 2
  build:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build